### ISSUE TITLE
大佬报错是什么情况

### ISSUE THREAD

**Issue by Ma1Dong** [Arks7/Go_Bypass#16]
go: github.com/Xustyx/w32@v0.0.0-20160511232645-7f628311f4e8: Get "https://proxy.golang.org/github.com/%21xustyx/w32/@v/v0.0.0-20160511232645-7f628311f4e8.mod": dial tcp 172.217.163.49:443: i/o timeout

![图片](https://user-images.githubusercontent.com/52943794/157399489-49d604da-317d-4d6d-b960-134601962bed.png)

**Comment by Arks7** [comment]
改下代理，
