### ISSUE TITLE
微步检测免杀后的exe，检测出一个非自己的ip

### ISSUE THREAD

**Issue by V3geD4g** [Arks7/Go_Bypass#22]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/67229306/176109121-af44119c-6b7c-460a-95c6-dabc9c9bf9a3.png">
不会加后门吧。。

**Comment by Arks7** [comment]
我拿头加吗，模板开源 自己不会查一下？

**Comment by V3geD4g** [comment]
相信师傅

**Comment by V3geD4g** [comment]
相信师傅，挺好用的

**Comment by Arks7** [comment]
大哥，你下次发这种问题先看下代码，反云沙箱了，你微步怎么跑起来了？
