### ISSUE TITLE
BUG Go_Bypass-master/In/template.go:29 +0x254

### ISSUE THREAD

**Issue by winezer0** [Arks7/Go_Bypass#25]
![image](https://user-images.githubusercontent.com/46115146/176916333-95c250a1-1cc4-4962-9b5f-606d64828f7f.png)

**Comment by Arks7** [comment]
It's not a BUG, you try downloading the packagego mod download
go get github.com/gonutz/ide/w32

**Comment by DevFil** [comment]
same error. tried with _go mod download_ and downloading packages manually but dont works.

**Comment by Arks7** [comment]
After running it once, a 1.go file will be generated in the in/template directory, cd will go in, and go build 1.go will try to download the package

**Comment by winezer0** [comment]
感谢，明天测试一下

**Comment by winezer0** [comment]
Thanks. I'll test it tomorrow

**Comment by winezer0** [comment]
TEST OK  !!!
