### ISSUE TITLE
大佬，请问这部分该怎么填

### ISSUE THREAD

**Issue by LoserFox** [Arks7/Go_Bypass#28]
![image](https://user-images.githubusercontent.com/57448027/179663637-f193f678-2ee8-4961-8633-24745a19fbe8.png)

**Comment by Arks7** [comment]
看问题解决方法

**Comment by LoserFox** [comment]
go mod download
go get github.com/gonutz/ide

**Comment by LoserFox** [comment]
查到了,,,是golang版本问题，您用的是1,17，我用的是最新的1.18

**Comment by LoserFox** [comment]
把Golang版本切到1.17重新配置环境也没有用，仍然是编译出错

**Comment by furuanruan** [comment]
> 

同问题，解决了吗？

**Comment by furuanruan** [comment]
已解决：输入go后回车能正常编译，但是加了C2 Profile后win11依然无法上线

**Comment by LoserFox** [comment]
> 已解决：输入go后回车能正常编译，但是加了C2 Profile后win11依然无法上线

请问您那边是如何进行配置后修复的

**Comment by furuanruan** [comment]
我这边是下载后运行这两条命令：
go mod download
go get github.com/gonutz/ide
然后出现：请输入Build方式......时输入
go
回车就好了

**Comment by Arks7** [comment]
稍后我会优化一下

**Comment by LoserFox** [comment]
> 稍后我会优化一下

麻烦大佬了，谢谢大佬提供这么好的软件

**Comment by Arks7** [comment]
已优化，重新拉取
