### ISSUE TITLE
表哥，为什么没有反应

### ISSUE THREAD

**Issue by shincehor** [Arks7/Go_Bypass#3]
![image](https://user-images.githubusercontent.com/56705317/147844719-f483b9b5-b559-4463-a112-d6a15a22f0bf.png)

**Comment by Arks7** [comment]
你这个我看毛啊，看看根目录有没有exe出现

**Comment by shincehor** [comment]
没有

**Comment by shincehor** [comment]
![image](https://user-images.githubusercontent.com/56705317/147865096-244aff10-e93c-4160-bad3-98c25e4b72a8.png)
没有
