### ISSUE TITLE
加密方式只有ECB能用

### ISSUE THREAD

**Issue by h2so0o4** [Arks7/Go_Bypass#6]
使用其他加密方式报错
![image](https://user-images.githubusercontent.com/49434585/148212228-44f51fdc-c7b6-4716-a224-8306594893a4.png)

**Comment by Arks7** [comment]
收到

**Comment by Arks7** [comment]
我看了下，是没问题的，其他加密方式必须16位
// 高级加密标准（Advanced Encryption Standard，AES) 又称Rijndael加密法
// AES中常见的有三种解决方案，分别为AES-128、AES-192和AES-256。如果采用真正的128位加密技术甚至256位加密技术，蛮力攻击要取得成功需要耗费相当长的时间
// AES 有五种加密模式：
// 电码本模式（Electronic Codebook Book (ECB)）、
// 密码分组链接模式（Cipher Block Chaining (CBC)）、
// 计算器模式（Counter (CTR)）、
// 密码反馈模式（Cipher FeedBack (CFB)）
// 输出反馈模式（Output FeedBack (OFB)）

**Comment by layou233** [comment]
GCM加密模式能支持吗
